### ISSUE TITLE
Not able to build with the readme specified steps

### ISSUE THREAD

**Issue by arun-madhavan-013** [rdkcentral/Thunder#1093]
CMake Error at Source/WPEFramework/GenericConfig.cmake:310 (message):
  ( ✿ ◠ ‿ ◠ ) FIXME: If you hit this error you are 'the choosen one'
  to fix the generic config using the ConfigGenerator
Call Stack (most recent call first):
  Source/WPEFramework/CMakeLists.txt:92 (include)

-- Configuring incomplete, errors occurred!

**Comment by pwielders** [comment]
This is the preparation for the new CMake (3.22 or higher) that does not support several features that where used to generate te config. Configs are now created using the Python. Should be all fixed on the latest greatest,
