### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by syed-ahmad-consult-red** [rdkcentral/Thunder#1259]
cmake -HThunder/Tools -Bbuild/ThunderTools       -DCMAKE_INSTALL_PREFIX=${THUNDER_INSTALL_DIR}/usr
CMake Error: The source directory "/home/vagrant/thunder/Thunder/Thunder/Tools" does not exist.

**Comment by pwielders** [comment]
Missing a bit of the context here, but the tools have recently be moved out of this repository into its own repository. See [ThunderTools ](https://github.com/RDKCentral/ThunderTools). You need to first install this as a package before you can install/compile anything of Thudner.

**Comment by woutermeek** [comment]
@syed-ahmad-consult-red does @pwielders his comment resolve your problem? If not please re-open the ticket.
