### ISSUE TITLE
SmartLinkType<> uses private member from LinkType<>

### ISSUE THREAD

**Issue by gladish** [rdkcentral/Thunder#151]
/home/gladish/work/Thunder/Thunder/Source/core/../websocket/JSONRPCLink.h: In member function ‘uint32_t WPEFramework::JSONRPC::SmartLinkType<I NTERFACE>::Invoke(const char*, const WPEFramework::Core::JSON::VariantContainer&, WPEFramework::Core::JSON::VariantContainer&, uint32_t) [with  INTERFACE = WPEFramework::Core::JSON::IElement; uint32_t = unsigned int]’:
/home/gladish/work/Thunder/Thunder/Source/core/../websocket/JSONRPCLink.h:1511:160: error: ‘constexpr const uint32_t WPEFramework::JSONRPC::Li nkType<WPEFramework::Core::JSON::IElement>::DefaultWaitTime’ is private within this context
  char method[], const Core::JSON::VariantContainer& parameters, Core::JSON::VariantContainer& response, const uint32_t waitTime = Client::Def aultWaitTime)
                                                                                                                                   ^~~~~~
/home/gladish/work/Thunder/Thunder/Source/core/../websocket/JSONRPCLink.h:572:35: note: declared private here
         static constexpr uint32_t DefaultWaitTime = 10000;

There are two DefaultWaitTime in that source file, I'm not sure which one was intended.

**Comment by MFransen69** [comment]
Hi Gladish,

Sorry for not getting back sooner. I just reproduced the problem and I'm looking into it.

Best, Marcel

**Comment by MFransen69** [comment]
Hi Gladish, 

The problems have been fixed and it should compile now. The multiple DeafutlWaitTime definitions were not intentional and we will do some cleanup later.

Best, Marcel
