### ISSUE TITLE
Add option to configure plugin to use data/persistent/volatile paths of 'main' callsign

### ISSUE THREAD

**Issue by emutavchi** [rdkcentral/Thunder#154]
For example, WebKitBrowser plugin has multiple 'alias' callsigns that use Shared Data/Persistent/Volatile paths derived from their name.

The request is to have a way to define/configure what 'alias' callsigns should be using.

**Comment by pwielders** [comment]
Resolved. You can now configure a persistentpostfix and a volatilepostfix. These postfixes will be added to the PersistentPath and VolatilePath in stead of the Callsign, if they are configured and not empty. This means that if two instances of a plugin need to use the same persitent location, configure these persistentpostfix/volatilepostfix of the plugin to the same value and you are good to go...
