### ISSUE TITLE
pthread mutex crash on activate plugins

### ISSUE THREAD

**Issue by laurence-ejraee** [rdkcentral/Thunder#1707]
Hi all,
I am attempting to upgrade to WPEFramework R4.4.2 however I am hitting this error at runtime when activating any plugin.

**WPEFramework: pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.**

Example code causing the crash:
`_controllerXappClient = _client->Open<Thunder::PluginHost::IShell>(_T("TimeSync"), ~0, 3000);`
`if (_controllerXappClient != nullptr) {`
`    _controllerXappClient->Release();`
`}`

If I comment out the Release() call the crash is not seen.
This same code worked on my older wpeframework build which is around 3 years old.

Any help or guidance much appreciated! Thanks.

**Comment by pwielders** [comment]
@HaseenaSainul could you analyse this ?

**Comment by HaseenaSainul** [comment]
> @HaseenaSainul could you analyse this ?

Sure @pwielders

**Comment by laurence-ejraee** [comment]
Hi all, just to update it seems the issue is not seen on R5.0.0.
I saw pthread related changes in Thunder repo which perhaps fix the issue.

**Comment by HaseenaSainul** [comment]
> Hi all, just to update it seems the issue is not seen on R5.0.0. I saw pthread related changes in Thunder repo which perhaps fix the issue.
Ok, this is only R4.4.2 version then, right. Are you getting the issue with any plugins, means metro plugins as well ?
Let me try to reproduce with buildroot build on RPI3

**Comment by laurence-ejraee** [comment]
I only tested with our custom plugin, and with the TimeSync plugin, but both saw the same issue.

**Comment by HaseenaSainul** [comment]
> I only tested with our custom plugin, and with the TimeSync plugin, but both saw the same issue.

Ok

**Comment by HaseenaSainul** [comment]
@laurence-ejraee , in which platform you are trying this ? are you used yocto or buildroot build ? I tried with buildroot not seeing crash. Is it possible to provide the custom plugin ?

**Comment by laurence-ejraee** [comment]
Used the buildroot build, using branch R4_4 https://github.com/WebPlatformForEmbedded/buildroot and the build is for our Broadcom platform.
Apologies, I am unable to share our custom plugin, however the issue should be seen with the code above using TimeSync plugin. If you cannot reproduce it may be specific to our setup.
Thanks.

**Comment by HaseenaSainul** [comment]
> Used the buildroot build, using branch R4_4 https://github.com/WebPlatformForEmbedded/buildroot and the build is for our Broadcom platform. Apologies, I am unable to share our custom plugin, however the issue should be seen with the code above using TimeSync plugin. If you cannot reproduce it may be specific to our setup. Thanks.

Thanks @laurence-ejraee, I used RPI3 platform

**Comment by laurence-ejraee** [comment]
Issue is not seen in R5 so closing
