### ISSUE TITLE
make failure

### ISSUE THREAD

**Issue by deondavis** [rdkcentral/Thunder#261]
`$ mkdir build && cd build`
`$ cmake ../ -DVIRTUALINPUT=ON -DVIRTUALINPUT_TOOLS=OFF`
`$ make -j16`

Platform PC_UNIX

_gave the following error_

thunder_development/Thunder/Source/tracing/../core/IPFrame.h: In member function ‘WPEFramework::Core::NodeId& WPEFramework::Core::TCPFrameType<SIZE>::Source() const’:
/mnt/23325514-5552-429f-9fd7-decadfe61ebd/elxsi/thunder_development/Thunder/Source/tracing/../core/IPFrame.h:199:89: error: cannot bind non-const lvalue reference of type ‘WPEFramework::Core::NodeId&’ to an rvalue of type ‘WPEFramework::Core::NodeId’
  199 |             return (result.IsValid() ? NodeId(result, ntohs(tcpHeader->source)) : result);
      |                                                                                         ^
/mnt/23325514-5552-429f-9fd7-decadfe61ebd/elxsi/thunder_development/Thunder/Source/tracing/../core/IPFrame.h: In member function ‘WPEFramework::Core::NodeId& WPEFramework::Core::TCPFrameType<SIZE>::Destination() const’:
/mnt/23325514-5552-429f-9fd7-decadfe61ebd/elxsi/thunder_development/Thunder/Source/tracing/../core/IPFrame.h:211:87: error: cannot bind non-const lvalue reference of type ‘WPEFramework::Core::NodeId&’ to an rvalue of type ‘WPEFramework::Core::NodeId’
  211 |             return (result.IsValid() ? NodeId(result, ntohs(tcpHeader->dest)) : result);
      |                                                                                       ^
/mnt/23325514-5552-429f-9fd7-decadfe61ebd/elxsi/thunder_development/Thunder/Source/tracing/../core/IPFrame.h: In member function ‘WPEFramework::Core::NodeId& WPEFramework::Core::UDPFrameType<SIZE>::Source() const’:
/mnt/23325514-5552-429f-9fd7-decadfe61ebd/elxsi/thunder_development/Thunder/Source/tracing/../core/IPFrame.h:259:89: error: cannot bind non-const lvalue reference of type ‘WPEFramework::Core::NodeId&’ to an rvalue of type ‘WPEFramework::Core::NodeId’
  259 |             return (result.IsValid() ? NodeId(result, ntohs(udpHeader->source)) : result);
      |                                                                                         ^
/mnt/23325514-5552-429f-9fd7-decadfe61ebd/elxsi/thunder_development/Thunder/Source/tracing/../core/IPFrame.h: In member function ‘WPEFramework::Core::NodeId& WPEFramework::Core::UDPFrameType<SIZE>::Destination() const’:
/mnt/23325514-5552-429f-9fd7-decadfe61ebd/elxsi/thunder_development/Thunder/Source/tracing/../core/IPFrame.h:271:87: error: cannot bind non-const lvalue reference of type ‘WPEFramework::Core::NodeId&’ to an rvalue of type ‘WPEFramework::Core::NodeId’
  271 |             return (result.IsValid() ? NodeId(result, ntohs(udpHeader->dest)) : result);

**Comment by pwielders** [comment]
What GCC version are you using to compile?

**Comment by deondavis** [comment]
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

**Comment by pwielders** [comment]
It is indeed the compiler correctly pointing out an error. Fixed by pullrequest:
https://github.com/rdkcentral/Thunder/pull/294
