### ISSUE TITLE
align, to_string and strtof functions

### ISSUE THREAD

**Issue by vijs** [rdkcentral/Thunder#27]
align, to_string and strtof functions aren't available in certain toolchains with an older version of gcc and this causes thunder build failure

Missing "#include <stdio.h>" in Source/ocdm/open_cdm.h

**Comment by pwielders** [comment]
As we do not yet have the same environment as you have for the RDK-B, can I ask you to validate if the changes made to Thunder are sufficient. I removed the dependencies on: align, to_string and strtof. Further more added the missing include. So I am hoping it is good to go now for building with the 4.8 compiler.
Branch: https://github.com/rdkcentral/Thunder/tree/development/RDK_B_Preparations

**Comment by pwielders** [comment]
Integrated into the master. Tested on RPI. No regression.

**Comment by vijs** [comment]
Thanks. Can you check on the const iterator when you get a chance?

`Index: git/Source/WPEFramework/Controller.cpp`
`===================================================================`
--- git.orig/Source/WPEFramework/Controller.cpp
+++ git/Source/WPEFramework/Controller.cpp
@@ -413,7 +413,7 @@ namespace Plugin {
`        if ((plugin->State() == PluginHost::IShell::ACTIVATED) && (_resumes.size() > 0)) {
             string callsign(plugin->Callsign());`
`-            std::list<string>::const_iterator index(_resumes.begin());`
`+            std::list<string>::iterator index(_resumes.begin());`
`             ASSERT(_service != nullptr);`

`Index: git/Source/core/Queue.h`
`===================================================================`
--- git.orig/Source/core/Queue.h
+++ git/Source/core/Queue.h
@@ -75,7 +75,7 @@ namespace Core {
`             m_Admin.Lock();
             if (m_State != DISABLED) {`
`-                typename std::list<CONTEXT>::const_iterator`
`+                typename std::list<CONTEXT>::iterator`
`                     index
                     = std::find(m_Queue.begin(), m_Queue.end(), a_Entry);`

**Comment by 2raghu** [comment]
> Thanks. Can you check on the const iterator when you get a chance?
> 
> `Index: git/Source/WPEFramework/Controller.cpp`
> `===================================================================`
> --- git.orig/Source/WPEFramework/Controller.cpp
> +++ git/Source/WPEFramework/Controller.cpp
> @@ -413,7 +413,7 @@ namespace Plugin {
> ` if ((plugin->State() == PluginHost::IShell::ACTIVATED) && (_resumes.size() > 0)) { string callsign(plugin->Callsign());`
> `- std::list<string>::const_iterator index(_resumes.begin());`
> `+ std::list<string>::iterator index(_resumes.begin());`
> ` ASSERT(_service != nullptr);`
> 
> `Index: git/Source/core/Queue.h`
> `===================================================================`
> --- git.orig/Source/core/Queue.h
> +++ git/Source/core/Queue.h
> @@ -75,7 +75,7 @@ namespace Core {
> ` m_Admin.Lock(); if (m_State != DISABLED) {`
> `- typename std::list<CONTEXT>::const_iterator`
> `+ typename std::list<CONTEXT>::iterator`
> ` index = std::find(m_Queue.begin(), m_Queue.end(), a_Entry);`

Why do you think const_iterator is issue here? Isn't it safe to have the index var to not get modified. Thanks.

**Comment by vijs** [comment]
const_iterator is not available in older GCC versions and the build fails in some of our RDK devices. We originally thought of a patch, but later decided to get it fixed in master.

**Comment by woutermeek** [comment]
@vijs can we close this issue, or is this still an issue?

**Comment by woutermeek** [comment]
Closing, problem seems resolved.
