### ISSUE TITLE
Activation & JSON RPC connection succeeds on non-existent services

### ISSUE THREAD

**Issue by varumugam123** [rdkcentral/Thunder#280]
It looks like through CPP implementation activating a non-existent service is possible. This further allows creating clients to that service and making requests possible.

Please refer the attached source file [test_cpp.txt] (https://github.com/rdkcentral/Thunder/files/5236712/test_cpp.txt) which I compiled with below command
`${CXX} ~/Tests/test.cpp -o ~/Tests/test ${CXXFLAGS} -lWPEFrameworkCore -lWPEFrameworkDefinitions -lWPEFrameworkProtocols -lWPEFrameworkPlugins -lstdc++ -lWPEFrameworkSecurityUtil -lm -lWPEFrameworkTracing`

The output is like
```
root@arrisxi6:/tmp# ./test abc
SecurityAgent end point /tmp/securityagent
SecurityAgent: Creating Token for http://localhost
-     L1 [23369]: "Message: {"id":1,"method":"status@abc"} send"
Plugin "abc" is not active, error=22
-     L1 [23369]: "Message: {"id":2,"method":"activate","params":{"callsign":"abc"}} send"
Activating plugin "abc" was successful, error=0
-     L1 [23369]: "Message: {"id":3,"method":"status@abc"} send"
Plugin "abc" is not active, error=22
-     L1 [23369]: "Message: {"id":4,"method":"abc.register","params":{ "event": "dummy", "id": ""}} send"
Subscription succeeded
-     L1 [23369]: "Message: {"id":5,"method":"abc.unregister","params":{ "event": "dummy", "id": ""}} send"
===== $$ [23369]: ASSERT [/usr/include/WPEFramework/core/JSONRPC.h:636] ((index != _handlers.end()) && _T("Do not unregister methods that are not registered!!!"))
Aborted (core dumped)
root@arrisxi6:/tmp#
```

As you can see, I could activate plugins "abc" and subscribe for an event "dummy" after creating a client for it. But "Unsubscribe()" leads to crash.

So below should be addressed
1) Should activate() request for non-existing services should be failed by returning appropriate error (22)?
2) Should client creation for non-existing services fail?
3) Should subscription for events (non-existing) fail and return error?

Note:
activation through curl command fails with proper error code
```
curl -v -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.aHR0cDovL2xvY2FsaG9zdA.qHyquZp7LWHLeqWpFo-aPqgNCEc9daNDU61g5BEaU1Q" -H "Content-Type: application/json" -X POST -d {"jsonrpc":"2.0","id":1,"method":Controller.1.activate, "params":{"callsign":"abc"}} http://127.0.0.1:9998/jsonrpc
{"jsonrpc":"2.0","id":1,"error":{"code":22,"message":"ERROR_UNKNOWN_KEY"}}
```

**Comment by pwielders** [comment]
Can you submit a pull request to fix this. You already have the test case to test it :-)

**Comment by pwielders** [comment]
If I am not mistaken this was regression and has been fixed.
