### ISSUE TITLE
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=284) before we can accept your contribution.<br/><hr/>**Alexandr Gavriliuc** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=284) it.</sub>

### ISSUE THREAD

**Issue by Gavriliuk** [rdkcentral/Thunder#293]
I have signed the CLA but GitHub asks me to do this again

[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=284) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/rdkcentral/Thunder?pullRequest=284) before we can accept your contribution.<br/><hr/>**Alexandr Gavriliuc** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/rdkcentral/Thunder?pullRequest=284) it.</sub>

_Originally posted by @CLAassistant in https://github.com/rdkcentral/Thunder/pull/284#issuecomment-695986686_

**Comment by mhughesacn** [comment]
Hi Alexandr: Usually this happens because you are using multiple emails, and you have to add them to your github account as in the link above.  Please check for this.  Martin
