### ISSUE TITLE
SharedBuffer.h const type casting throws error on gcc 9.x

### ISSUE THREAD

**Issue by moorthy-bs** [rdkcentral/Thunder#369]
error log:
`|...build-rpi-hyb/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/libcobalt/20.lts.stable-1/recipe-sysroot/usr/include/WPEFramework/core/SharedBuffer.h:132:80: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
|   132 |             _administration->_bytesWritten = static_cast<const uint32_t>(Size());
|       |                                                                                ^
| ...build-rpi-hyb/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/libcobalt/20.lts.stable-1/recipe-sysroot/usr/include/WPEFramework/core/SharedBuffer.h: In member function 'uint32_t WPEFramework::Core::SharedBuffer::Consumed()':
| ...build-rpi-hyb/tmp/work/cortexa7t2hf-neon-vfpv4-rdk-linux-gnueabi/libcobalt/20.lts.stable-1/recipe-sysroot/usr/include/WPEFramework/core/SharedBuffer.h:159:80: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
|   159 |             _administration->_bytesWritten = static_cast<const uint32_t>(Size());
|       |                                                                                ^`

Possible solution:
to avoid such warning/error, the _const_ type can be removed on static cast

**Comment by woutermeek** [comment]
closing because the PR is merged
