### ISSUE TITLE
Standalone build broken

### ISSUE THREAD

**Issue by WizzerWorks** [rdkcentral/Thunder#425]
Is this code supposed to build outside the RDK yocto environment?

Attempted to build on Ubuntu 18.04 LTS 64-bit platform using cmake version 3.10.2. The following error occurred:

cmake ~/Projects/Thunder/
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting up WPEFramework v1.0.0
-- Building on Linux
-- Looking for __GNU_LIBRARY__
-- Looking for __GNU_LIBRARY__ - found
CMake Error at CMakeLists.txt:51 (find_package):
  By not providing "FindProxyStubGenerator.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ProxyStubGenerator", but CMake did not find one.

  Could not find a package configuration file provided by
  "ProxyStubGenerator" with any of the following names:

    ProxyStubGeneratorConfig.cmake
    proxystubgenerator-config.cmake

  Add the installation prefix of "ProxyStubGenerator" to CMAKE_PREFIX_PATH or
  set "ProxyStubGenerator_DIR" to a directory containing one of the above
  files.  If "ProxyStubGenerator" provides a separate development package or
  SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/msm/Projects/Thunder/build/CMakeFiles/CMakeOutput.log".

**Comment by WizzerWorks** [comment]
I got around this issue by doing the following:

1. mkdir build-tools
2. cd build-tools
3. cmake ~/Projects/Thunder/Tools
4. sudo make install

**Comment by pwielders** [comment]
Indeed you first need to install the tools (JSONRPC Code generator and COMRPC ProxyStb code generatr) and only than you can build the Thunder libray. Will updat the documentation to reflect this accordingly.
