### ISSUE TITLE
Unit tests don't link

### ISSUE THREAD

**Issue by gladish** [rdkcentral/Thunder#539]
[ 44%] Linking CXX executable WPEFramework_test_core
/usr/bin/ld: CMakeFiles/WPEFramework_test_core.dir/test_messageException.cpp.o: in function `test_messageException_simple_messageException_Test::TestBody()':
/home/gladish/work/thunder/Thunder/Tests/unit/core/test_messageException.cpp:31: undefined reference to `WPEFramework::Core::MessageException::MessageException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: /home/gladish/work/thunder/Thunder/Tests/unit/core/test_messageException.cpp:32: undefined reference to `WPEFramework::Core::MessageException::Message() const'
/usr/bin/ld: /home/gladish/work/thunder/Thunder/Tests/unit/core/test_messageException.cpp:34: undefined reference to `WPEFramework::Core::MessageException::MessageException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
/usr/bin/ld: /home/gladish/work/thunder/Thunder/Tests/unit/core/test_messageException.cpp:41: undefined reference to `WPEFramework::Core::MessageException::Message() const'
/usr/bin/ld: /home/gladish/work/thunder/Thunder/Tests/unit/core/test_messageException.cpp:47: undefined reference to `WPEFramework::Core::MessageException::Message() const'
/usr/bin/ld: /home/gladish/work/thunder/Thunder/Tests/unit/core/test_messageException.cpp:34: undefined reference to `WPEFramework::Core::MessageException::~MessageException()'
/usr/bin/ld: /home/gladish/work/thunder/Thunder/Tests/unit/core/test_messageException.cpp:31: undefined reference to `WPEFramework::Core::MessageException::~MessageException()'
/usr/bin/ld: CMakeFiles/WPEFramework_test_core.dir/test_tracing.cpp.o: in function `WPEFramework::Trace::TraceType<WPEFramework::Trace::Information, &Tracing>::TraceControl<WPEFramework::Trace::Information, &Tracing>::TraceControl()':
/home/gladish/work/thunder/Thunder/Source/tracing/TraceControl.h:91: undefined reference to `Tracing'
/usr/bin/ld: CMakeFiles/WPEFramework_test_core.dir/test_tracing.cpp.o: in function `WPEFramework::Trace::TraceType<WPEFramework::Trace::Information, &Tracing>::TraceControl<WPEFramework::Trace::Information, &Tracing>::Module() const':
/home/gladish/work/thunder/Thunder/Source/tracing/TraceControl.h:114: undefined reference to `Tracing'
collect2: error: ld returned 1 exit status
make[2]: *** [Tests/unit/core/CMakeFiles/WPEFramework_test_core.dir/build.make:855: Tests/unit/core/WPEFramework_test_core] Error 1
make[1]: *** [CMakeFiles/Makefile2:322: Tests/unit/core/CMakeFiles/WPEFramework_test_core.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by woutermeek** [comment]
@gladish is this issue still relevant? If so please re-open and we will look into it.
