### ISSUE TITLE
Documentation Request for Execution HowTo

### ISSUE THREAD

**Issue by WizzerWorks** [rdkcentral/Thunder#561]
Is there any documentation available for how to execute Thunder? I have built the WPEFramework and WPEProcess binaries for Ubuntu 18.04 LTS 64-bit and installed in a local (non-system) directory.

Are there configuration files or options that need to be passed in?

FYI: I have also built the ThunderUI for testing.

**Comment by WizzerWorks** [comment]
I was able to start execution using:

sudo ${THUNDER_INSTALL_DIR}/bin/WPEFramework -c ${THUNDER_INSTALL_DIR}/../etc/WPEFramework/config.json

I also had to set LD_LIBRARY_PATH:

export $LD_LIBRARY_PATH=${THUNDER_INSTALL_DIR}/lib

**Comment by pwielders** [comment]
We are currently integrating visualCode on Linux with proper configurations files so you can run it from VisualStudio. @bramoosterhuis can you share the locations of these files (or any documentation we have?)

**Comment by WizzerWorks** [comment]
I was able to start WPEFramework and start the ThunderUI on non-RDK Ubuntu 18.04 LTS platform. I didn't build or attempt to install RDKServices. My intent is to use WPEFramework independent of RDK. So I am looking for information on how to do this.

Is this on the WPEFramework team radar? To maintain and support non-RDK platforms?

**Comment by pwielders** [comment]
Definitly as we are delivering ourselves solutions outsode of the RDK framework as well :-)
