### ISSUE TITLE
add additional search path in the "activate()" API in order to support downloadable plugins

### ISSUE THREAD

**Issue by goruklu** [rdkcentral/Thunder#940]
We'd like to be able to download some resources/libraries needed by an out-of-process thunder plugin. Due to the way lazy loading
works on Linux, we need to update LD_LIBRARY_PATH of the plugin with the location of the downloaded libraries.

Adding the additional path to the Controller's activate() [method  ](https://github.com/rdkcentral/Thunder/blob/master/Source/WPEFramework/doc/ControllerPlugin.md#method.activate)will let us download some resources anytime before an out-of-process plugin is activated.
<html>
<body>

Name | Type | Description
-- | -- | --
params | object |  
params.callsign | string | Plugin callsign
params.additionalLDLibPath | string | path to downloaded resources (optional)

</body>
</html>

```
{
    "jsonrpc": "2.0",
    "id": 42,
    "method": "Controller.1.activate",
    "params": {
        "callsign": "MyDownloadablePlugin",
        "additionalLDLibPath": "/additional/path/to/downloaded/libraries"
    }
}
```

**Comment by goruklu** [comment]
@pwielders please see the above per the discussions we had regarding DELIA-47496 "Make the LD_LIBRARY_PATH configurable for out-of-process-plugins"

**Comment by pwielders** [comment]
@goruklu I guess this s now part of R2 and R3 as discussed? And we can close the ticket?

**Comment by goruklu** [comment]
yes we can close this! thanks @pwielders
